services:
  # To run production: docker compose up
  # To run development: docker compose --profile dev up
  transit-tv-svelte:
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile
    image: transit-tv-svelte
    container_name: transit-tv-svelte
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "production"
      USE_SVELTE: "true"
    volumes:
      - ./logs:/app/logs
    networks:
      - transit-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    profiles:
      - production

  # Frontend build service - builds Svelte app independently
  frontend-builder:
    image: node:24-alpine
    container_name: frontend-builder
    working_dir: /app/svelte-app
    volumes:
      - ./svelte-app:/app/svelte-app
      - frontend_modules:/app/svelte-app/node_modules
    networks:
      - transit-network
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm run build"
    profiles:
      - build

  # Backend build service - builds server independently
  backend-builder:
    image: node:24-alpine
    container_name: backend-builder
    working_dir: /app
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - backend_modules:/app/node_modules
    networks:
      - transit-network
    command: >
      sh -c "npm install -g pnpm && pnpm install --prod"
    profiles:
      - build

  # Development service - Svelte with hot reload
  # Note: For development, it's recommended to run locally:
  #   Terminal 1: cd svelte-app && pnpm dev
  #   Terminal 2: USE_SVELTE=true pnpm start
  # This provides better performance and easier debugging than Docker.
  transit-tv-dev:
    image: node:24-alpine
    container_name: transit-tv-dev
    working_dir: /app/svelte-app
    restart: "no"
    ports:
      - "5173:5173"  # Vite dev server
    environment:
      NODE_ENV: "development"
      CI: "true"
    env_file:
      - .env.docker
    volumes:
      - ./svelte-app:/app/svelte-app
      - dev_svelte_modules:/app/svelte-app/node_modules
    networks:
      - transit-network
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm run dev -- --host 0.0.0.0"
    profiles:
      - dev

  # Backend service for development (pairs with transit-tv-dev)
  transit-tv-backend:
    image: node:24-alpine
    container_name: transit-tv-backend
    working_dir: /app
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "development"
      USE_SVELTE: "false"
      CI: "true"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - dev_modules:/app/node_modules
    networks:
      - transit-network
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             node server/app.js"
    profiles:
      - dev

volumes:
  frontend_modules:
  backend_modules:
  dev_modules:
  dev_svelte_modules:

networks:
  transit-network:
    driver: bridge