# ==============================================================================
# Optimized Docker Compose Configuration
# ==============================================================================
# Changes from compose.dev.yaml:
# 1. Use corepack instead of npm install -g pnpm
# 2. Add heap size limits for stability
# 3. Updated command syntax for better readability
#
# Usage:
#   Production: docker compose -f compose.optimized.yaml up -d
#   Development: docker compose -f compose.optimized.yaml --profile dev up
# ==============================================================================

services:
  # Production service using optimized Dockerfile
  transit-tv-svelte:
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile.optimized
    image: transit-tv-svelte:optimized
    container_name: transit-tv-svelte
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: 'production'
      USE_SVELTE: 'true'
    volumes:
      - ./logs:/app/logs
    networks:
      - transit-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    profiles:
      - production

  # Frontend builder service
  frontend-builder:
    image: node:24-alpine
    container_name: frontend-builder
    working_dir: /app/svelte-app
    volumes:
      - ./svelte-app:/app/svelte-app
      - frontend_modules:/app/svelte-app/node_modules
    networks:
      - transit-network
    command:
      - sh
      - -c
      - |
        corepack enable
        corepack prepare pnpm@latest --activate
        pnpm install
        pnpm run build
    profiles:
      - build

  # Backend builder service
  backend-builder:
    image: node:24-alpine
    container_name: backend-builder
    working_dir: /app
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - backend_modules:/app/node_modules
    networks:
      - transit-network
    command:
      - sh
      - -c
      - |
        corepack enable
        corepack prepare pnpm@latest --activate
        pnpm install --prod
    profiles:
      - build

  # Development service - Svelte with hot reload
  transit-tv-dev:
    image: node:24-alpine
    container_name: transit-tv-dev
    working_dir: /app/svelte-app
    restart: 'no'
    ports:
      - '5173:5173' # Vite dev server
    environment:
      NODE_ENV: 'development'
      CI: 'true'
    env_file:
      - .env.docker
    volumes:
      - ./svelte-app:/app/svelte-app
      - dev_svelte_modules:/app/svelte-app/node_modules
    networks:
      - transit-network
    command:
      - sh
      - -c
      - |
        corepack enable
        corepack prepare pnpm@latest --activate
        pnpm install
        pnpm run dev -- --host 0.0.0.0
    profiles:
      - dev

  # Backend service for development
  transit-tv-backend:
    image: node:24-alpine
    container_name: transit-tv-backend
    working_dir: /app
    restart: 'no'
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: 'development'
      USE_SVELTE: 'false'
      CI: 'true'
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - dev_modules:/app/node_modules
    networks:
      - transit-network
    command:
      - sh
      - -c
      - |
        corepack enable
        corepack prepare pnpm@latest --activate
        pnpm install
        node --max-old-space-size=400 server/app.js
    profiles:
      - dev

volumes:
  frontend_modules:
  backend_modules:
  dev_modules:
  dev_svelte_modules:

networks:
  transit-network:
    driver: bridge
