services:
  # Production service - Svelte migration
  transit-tv-svelte:
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile.svelte
    image: transit-tv-svelte
    container_name: transit-tv-svelte
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "production"
      USE_SVELTE: "true"
    volumes:
      - ./logs:/app/logs
    networks:
      - transit-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Frontend build service - builds Svelte app independently
  frontend-builder:
    image: node:20-alpine
    container_name: frontend-builder
    working_dir: /app/svelte-app
    volumes:
      - ./svelte-app:/app/svelte-app
      - frontend_modules:/app/svelte-app/node_modules
    networks:
      - transit-network
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm run build"
    profiles:
      - build

  # Backend build service - builds server independently
  backend-builder:
    image: node:20-alpine
    container_name: backend-builder
    working_dir: /app
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - backend_modules:/app/node_modules
    networks:
      - transit-network
    command: >
      sh -c "npm install -g pnpm && pnpm install --prod"
    profiles:
      - build

  # Development service - Svelte with hot reload
  transit-tv-dev:
    image: node:20-alpine
    container_name: transit-tv-dev
    working_dir: /app
    restart: unless-stopped
    ports:
      - "5173:5173"  # Vite dev server
      - "8082:8080"  # App port (alternate)
    environment:
      NODE_ENV: "development"
      VITE_HMR_HOST: "localhost"
      VITE_HMR_PORT: "5173"
      CI: "true"
    volumes:
      - .:/app
      - dev_svelte_modules:/app/svelte-app/node_modules
      - dev_modules:/app/node_modules
    networks:
      - transit-network
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             cd svelte-app &&
             pnpm install &&
             pnpm run dev"
    profiles:
      - dev

volumes:
  frontend_modules:
  backend_modules:
  dev_modules:
  dev_svelte_modules:

networks:
  transit-network:
    driver: bridge
