services:
  transit-tv:
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile
    image: transit-tv
    container_name: transit-tv
    restart: unless-stopped
    ports:
      - "8080:8080" # Default port for the application is 8080, change the left side if needed
    environment:
      NODE_ENV: "production"
      # These environment variables will override those in .env.docker if set
      # LOG_LEVEL: "info"
      
      # Theme customization examples (uncomment and modify as needed)
      # THEME_PRIMARY_COLOR: "#89CC04"  # brat green
      # THEME_PRIMARY_TEXT_COLOR: "#ffffff"
      # THEME_PRIMARY_LOGO: "/assets/custom/my-logo.svg"
      # THEME_SECONDARY_LOGO: "/assets/custom/agency-logo.svg"
      # THEME_SHOW_SECONDARY_LOGO: "true"
      # THEME_AGENCY_NAME: "Metro Transit"
    volumes:
      # Persist any data that needs to be saved between container restarts
      - ./logs:/app/logs # change this to your desired log directory
      
      # Custom assets (logos, images, etc.) - place your files in ./custom-assets/
      # - ./custom-assets:/app/client/assets/custom:ro
    networks:
      - transit-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  transit-network:
    driver: bridge
